### ISSUE TITLE
Some issues on Nostalrius

### ISSUE THREAD

**Issue by fgsfdss** [Cabro/BigWigs#2]
MC:
Baron Geddon can have a cooldown timer on the pulse, always seems to happen at a regular interval.
Shazzrah's timers are all really off, by so many seconds I couldn't even tell how many.
Ragnaros' initial knockback timer is off by a couple seconds.

BWL:
Razorgore can have a conflagrate timer, also seemingly regular interval.
Broodlord Lashlayer's Blast Wave cooldown is much longer than the current timer.
Chromaggus could use a frenzy timer (every 15 seconds flat).
Nefarian has a landing timer, which is useless as he lands upon killing 42 Drakonids. There should be a kill counter instead.

ZG:
Each time Bloodlord Mandokir watches someone you get an error pop-up.
High Priestess Arlokk's stealth phase timer is off by a few seconds.

**Comment by Cabro** [comment]
Yes, because this is for Feenix.
